# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 994e86f75e85e9fac63df6d60baea1bc27bfea1e3b0fcd9b8350b11bdf1804bbbb1fe31c6e89aac6f196de9fa9b4d319f71690d8fbd09a34b66867c5a55af842

test:
  secret_key_base: 3517a85569a66dcf0f0c2aa06776ec3d347ead81211142061b22ba828927e65c8ae6df2b1c8597c8b49f058e5cf2d740c10173895a83bceeb6e7fd7b92ad3537

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
